name: lrk10l
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.13.15
  - cd-hit
  - pyhmmer
  - hmmer
  - muscle
  - biopython
  - numpy
  - pandas
  - xgboost
  - scikit-learn
  - scikit-posthocs
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - joblib
  - pytorch
  - ipywidgets
  - pip
  - pip:
      - fair-esm